try out TF installation from https://github.com/rstudio/tensorflow/blob/main/.github/workflows/R-CMD-check.yaml

diff --git a/.github/workflows/R-CMD-check.yaml b/.github/workflows/R-CMD-check.yaml
--- a/.github/workflows/R-CMD-check.yaml
+++ b/.github/workflows/R-CMD-check.yaml
@@ -16,77 +16,124 @@ on:
 
 name: R-CMD-check
 
-concurrency:
-  group: ${{ github.workflow }}-${{ github.head_ref }}
-  cancel-in-progress: true
+defaults:
+  run:
+    shell: Rscript {0}
+
+# concurrency:
+#   group: ${{ github.workflow }}-${{ github.head_ref }}
+#   cancel-in-progress: true
 
 jobs:
   R-CMD-check:
-    runs-on: ${{ matrix.config.os }}
-
-    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
-
+    name: ${{ matrix.os }}, tf-${{ matrix.tf }}, R-${{ matrix.r}}
+    # runs-on: ${{ matrix.config.os }}
+    # name: ${{ matrix.config.os }} (${{ matrix.config.r }})
+    timeout-minutes: 30
     strategy:
       fail-fast: false
       matrix:
-        config:
-          - {os: macOS-latest,   r: 'release'}
-          - {os: windows-latest, r: 'release'}
-          - {os: windows-latest, r: 'oldrel'}
-          - {os: ubuntu-18.04,   r: 'devel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest", http-user-agent: "R/4.0.0 (ubuntu-18.04) R (4.0.0 x86_64-pc-linux-gnu x86_64 linux-gnu) on GitHub Actions" }
-          - {os: ubuntu-18.04,   r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"}
-          - {os: ubuntu-18.04,   r: 'oldrel-1', rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"}
-          - {os: ubuntu-18.04,   r: 'oldrel-2', rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"}
+        include:
+          - {os: 'ubuntu-latest' , tf: 'default', r: 'release'}
+          - {os: 'windows-latest', tf: 'default', r: 'release'}
+          - {os: 'macOS-latest'  , tf: 'default', r: 'release'}
 
+          - {os: 'ubuntu-latest' , tf: 'default', r: 'oldrel'}
+          - {os: 'windows-latest', tf: 'default', r: 'oldrel'}
+          - {os: 'macOS-latest'  , tf: 'default', r: 'oldrel'}
+
+          # - {os: 'ubuntu-20.04', tf: 'default', r: '3.6'} # default R in ubuntu-20.04
+          - {os: 'ubuntu-latest', tf: 'default', r: 'oldrel-1'}
+          - {os: 'ubuntu-latest', tf: 'default', r: 'oldrel-2'}
+          - {os: 'ubuntu-latest', tf: 'default', r: 'oldrel-3'}
+
+          ## uncomment if/when tf "release" != "default"
+          # - {os: 'ubuntu-20.04'  , tf: 'release', r: 'release'}
+          # - {os: 'windows-latest', tf: 'release', r: 'release'}
+          # - {os: 'macOS-latest'  , tf: 'release', r: 'release'}
+
+          - {os: 'ubuntu-latest', tf: '2.10', r: 'release'}
+          - {os: 'ubuntu-latest', tf: '2.9' , r: 'release'}
+          - {os: 'ubuntu-latest', tf: '2.7' , r: 'release'}
+          - {os: 'ubuntu-latest', tf: '2.6' , r: 'release'}
+          - {os: 'ubuntu-latest', tf: '2.5' , r: 'release'}
+
+          # these are allowed to fail
+          # - {os: 'ubuntu-20.04', tf: 'default', r: 'devel'}
+          # - {os: 'ubuntu-20.04', tf: 'nightly' , r: 'release'}
+          # - {os: 'ubuntu-20.04', tf: '2.7.0rc1', r: 'release'}
+    runs-on: ${{ matrix.os }}
+    continue-on-error: ${{ matrix.tf == 'nightly' || contains(matrix.tf, 'rc') || matrix.r == 'devel' }}
     env:
-      RSPM: ${{ matrix.config.rspm }}
+      R_REMOTES_NO_ERRORS_FROM_WARNINGS: 'true'
+      R_COMPILE_AND_INSTALL_PACKAGES: 'never'
       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
-      RETICULATE_AUTOCONFIGURE: 'FALSE'
-      TF_VERSION: '1.14.0'
 
     steps:
 
       - uses: actions/checkout@v2
 
       - uses: r-lib/actions/setup-r@v2
-        id: install-r
+        id: setup-r
         with:
-          r-version: ${{ matrix.config.r }}
-          http-user-agent: ${{ matrix.config.http-user-agent }}
+          r-version: ${{ matrix.r }}
+          Ncpus: '2L'
+          use-public-rspm: true
+
 
       - uses: r-lib/actions/setup-pandoc@v2
 
-      - uses: r-lib/actions/setup-r-dependencies@v2
+      - name: Get Date
+        id: get-date
+        shell: bash
+        run: |
+          echo "::set-output name=year-week::$(date -u "+%Y-%U")"
+          echo "::set-output name=date::$(date -u "+%F")"
+      - name: Restore R package cache
+        uses: actions/cache@v2
+        id: r-package-cache
         with:
-          cache-version: 2
-          extra-packages: |
-            local::.
-            any::keras
-            any::rcmdcheck
+          path: ${{ env.R_LIBS_USER }}
+          key: ${{ matrix.os }}-${{ steps.setup-r.outputs.installed-r-version }}-${{ steps.get-date.outputs.year-week }}-1
+
+      - name: Install remotes
+        if: steps.r-package-cache.outputs.cache-hit != 'true'
+        run: install.packages("remotes")
+
+      - name: Install system dependencies
+        if: runner.os == 'Linux'
+        shell: bash
+        run: |
+          . /etc/os-release
+          while read -r cmd
+          do
+            echo "$cmd"
+            sudo $cmd
+          done < <(Rscript -e "writeLines(remotes::system_requirements('$ID-$VERSION_ID'))")
+      - name: Install package + deps
+        run: remotes::install_local(dependencies = TRUE, force = TRUE)
 
       - name: Install Miniconda
-        run: |
-          reticulate::install_miniconda()
-        shell: Rscript {0}
-
-      - name: Set options for conda binary for macOS
-        if: runner.os == 'macOS'
-        run: |
-          echo "options(reticulate.conda_binary = reticulate:::miniconda_conda())" >> .Rprofile
+        run: reticulate::install_miniconda()
 
       - name: Install TensorFlow
-        run: |
-          cat("::group::Create Environment", sep = "\n")
-          reticulate::conda_create('r-reticulate', packages = c('python==3.7'))
-          cat("::endgroup::", sep = "\n")
+        run: tensorflow::install_tensorflow(version = '${{ matrix.tf }}-cpu')
 
-          cat("::group::Install Tensorflow", sep = "\n")
-          keras::install_keras(tensorflow = Sys.getenv('TF_VERSION'),
-              extra_packages = c('IPython', 'requests', 'certifi', 'urllib3', 'tensorflow-probability==0.7.0', 'numpy==1.16.4'))
-          cat("::endgroup::", sep = "\n")
-        shell: Rscript {0}
+      - name: Install rcmdcheck
+        run: remotes::install_cran("rcmdcheck")
 
+      - name: Check
+        run: rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'warning', check_dir = 'check')
 
+      - name: Show testthat output
+        if: always()
+        shell: bash
+        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
+
+      - name: Don't use tar from old Rtools to store the cache
+        if: ${{ runner.os == 'Windows' && startsWith(steps.install-r.outputs.installed-r-version, '3') }}
+        shell: bash
+        run: echo "C:/Program Files/Git/usr/bin" >> $GITHUB_PATH
       - name: Python + TF details
         run: |
           tensorflow::tf_config()
@@ -101,10 +148,6 @@ jobs:
           pkgs <- installed.packages()[, "Package"]
           sessioninfo::session_info(pkgs, include_base = TRUE)
         shell: Rscript {0}
-
-      - uses: r-lib/actions/check-r-package@v2
-        with:
-          args: 'c("--no-manual", "--as-cran", "--no-multiarch")'
 
       - name: Check on single core machine
         if: runner.os != 'Windows'
